<x-yomi::layout title="Início" :active="$active">
    <div class="page-head"><div><div class="eyebrow">● PAINEL DE LEITURA · EDIÇÃO NOTURNA</div><h1>Bom dia, {{ Str::of(auth()->user()->name ?? 'Leitor')->explode(' ')->first() }}.</h1><p>Seu histórico de leitura, organizado para o próximo capítulo.</p></div>        <div class="period-tabs"><span class="pill active">2024</span><span class="pill">Últimos 12 meses</span><a class="btn btn-primary" href="{{ route('yomi.library') }}"><x-yomi::icon icon="comece-registrar" class="btn-icon" /> Registrar leitura</a></div></div>
    <div class="dashboard-grid">
        <section class="panel hero-panel">
            @if($active)
                <div class="cover cover-hero">@if($cover($active->manga))<img src="{{ $cover($active->manga) }}" alt="Capa de {{ $active->manga->titulo }}">@endif<span class="cover-copy">{{ Str::limit($active->manga->titulo, 18) }}</span></div>
                <div class="hero-copy"><span class="meta">EM ANDAMENTO · {{ $active->manga->tipo ?? 'MANGÁ' }}</span><h2>{{ $active->manga->titulo }}</h2><p>{{ Str::limit($active->manga->sinopse ?? 'Uma leitura esperando por você.', 120) }}</p><div class="progress-meta"><span>Cap. {{ $active->ultimo_capitulo_lido ?? 0 }} / {{ $active->manga->capitulos_conhecidos ?? '?' }}</span><strong>{{ $active->manga->capitulos_conhecidos ? round(($active->ultimo_capitulo_lido ?? 0) / $active->manga->capitulos_conhecidos * 100) : 0 }}%</strong></div><div class="progress-line"><span style="width:{{ $active->manga->capitulos_conhecidos ? min(100, (($active->ultimo_capitulo_lido ?? 0) / $active->manga->capitulos_conhecidos) * 100) : 0 }}%"></span></div><br><form method="POST" action="{{ route('yomi.mangas.mark-next', $active->manga) }}">@csrf<button class="btn btn-primary" type="submit">✓ +1 Marcar próximo capítulo</button></form></div>
            @else
                <div class="empty-state" style="width:100%"><x-yomi::icon icon="comece-registrar" class="empty-icon" /><div class="eyebrow">SUA ESTANTE COMEÇA AQUI</div><h2>Nenhuma leitura em andamento</h2><p>Adicione uma obra à biblioteca para acompanhar sua jornada.</p><a class="btn btn-primary" href="{{ route('yomi.library') }}">Abrir biblioteca</a></div>
            @endif
        </section>
        <section class="panel queue-panel"><h2>Fila de leitura <span class="eyebrow">{{ $queue->count() }}</span></h2>@forelse($queue as $item)<a class="queue-card" href="{{ route('yomi.mangas.show', $item->manga) }}"><div class="cover cover-thumb">@if($cover($item->manga))<img src="{{ $cover($item->manga) }}" alt="">@endif</div><div class="queue-info"><strong>{{ $item->manga->titulo }}</strong><small>Cap. {{ $item->ultimo_capitulo_lido ?? 0 }} / {{ $item->manga->capitulos_conhecidos ?? '?' }}</small><div class="progress-line"><span style="width:{{ $item->manga->capitulos_conhecidos ? min(100, (($item->ultimo_capitulo_lido ?? 0) / $item->manga->capitulos_conhecidos) * 100) : 0 }}%"></span></div></div><span class="queue-action">›</span></a>@empty<div class="empty-state"><x-yomi::icon icon="proxima-leitura" class="empty-icon" />Sua fila está livre.</div>@endforelse</section>
    </div>
    <div class="section-row"><h2 class="section-title">Radar de novos capítulos</h2><a href="{{ route('yomi.library') }}">VER BIBLIOTECA →</a></div>
    <section class="release-list">@forelse($newChapters as $read)<div class="release"><i class="dot"></i><div><strong>{{ $read->capitulo->manga->titulo ?? 'Obra' }}</strong><small>Cap. {{ $read->capitulo->numero }} · registrado recentemente</small></div><span>✓</span></div>@empty<div class="empty-state" style="grid-column:1/-1">Seus capítulos registrados aparecerão aqui.</div>@endforelse</section>
    <section class="panel weekly"><div class="section-row" style="margin:0"><div><div class="section-kicker">RITMO SEMANAL</div><h2 class="section-title">{{ $weeklyTotal }} capítulos lidos <small style="color:var(--muted);font-size:12px">nos últimos 7 dias</small></h2></div><strong style="color:#f3a09b;font:700 24px 'Space Grotesk'">{{ $streak }} dias</strong></div><div class="bar-chart"><i style="height:35%"></i><i style="height:60%"></i><i style="height:28%"></i><i style="height:78%"></i><i style="height:48%"></i><i class="hot" style="height:88%"></i><i style="height:22%"></i></div><div class="bar-labels"><span>SEG</span><span>TER</span><span>QUA</span><span>QUI</span><span>SEX</span><span>SÁB</span><span>DOM</span></div></section>
</x-yomi::layout>
